adminapp/urls.py
from django.conf.urls import url
from adminapp import views
app_name = 'adminapp'
urlpatterns = [
url(r'^$', views.index, name="index"),
url(r'^vehicle_details/', views.vehicle_details, name="vehicle_details"),
url(r'^vehicle_category/$', views.vehicle_category, name="vehicle_category"),
url(r'^vehicle_company/$', views.vehicle_company, name="vehicle_company"),
url(r'^showdata/$', views.showdata, name="showdata"),
url(r'^updatedata/$', views.updatedata, name="updatedata"),
url(r'^delete_data/$', views.delete_data, name="delete_data"),
url(r'^queries/$', views.queries, name="queries")
]

front_app/urls.py
from django.conf.urls import url
from front_app import views


app_name = 'front_app'

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^error$',views.page_not_found,name="error"),
    url(r'^about/$',views.about,name="about"),
    url(r'^contact$',views.contact,name="contact"),
    url(r'^faq$',views.faq,name="faq"),
    url(r'^team$',views.help,name="team"),
    url(r'^login$', views.login, name="login"),
    url(r'^signup$', views.signup, name="signup"),
    url(r'^masteruser/$', views.master, name="master"),
    url(r'^forgetpassword/$', views.forgototp, name="forgetpassword"),
    url(r'^car-details/$', views.car_detail, name="car"),
    url(r'^update/$', views.profile, name="update"),
    url(r'^booking/$', views.booking, name="booking"),
    url(r'^invoice/$', views.invoice, name="invoice"),
    url(r'^confirm_booking/', views.confirm_booking),
    url(r'^show_bookings/', views.show_bookings),
url(r'^view_bookings/', views.view_current_book),
    url(r'^cancel_booking/', views.cancel_booking),
    url(r'^queries/', views.queries),
url(r'^user/', views.user_index)



]

vehicle_hire/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from front_app import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^logout/',views.logout ), # url for logout
    url(r'^', include('front_app.urls')),
    url(r'^superuser/', include('adminapp.urls',namespace="superuser")),
    url(r'^manager/', include('managerapp.urls')),
    url(r'^businessuser/', include('businessuserapp.urls')),
    url(r'^changepassword/',views.updatepassword),
    url(r'^profileupdate/',views.profile),
    url(r'^policy/',views.policy),
url(r'^feepolicy/',views.feepolicy),
url(r'^member/',views.member),
url(r'^privacy/',views.privacy),
url(r'^eligibilty/',views.eligibilty),

    url(r'^dskjgheriugiurefhkusdjdowieuqhiurehf/',views.verify)
    #url(r'^fpassword/',views.fpassword)

]\
              +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

templates/contact.html
{% extends 'master.html' %}
{% block content %}
    <section id="page-title-area" class="section-padding overlay">
        <div class="container">
            <div class="row">
                <!-- Page Title Start -->
                <div class="col-lg-12">
                    <div class="section-title  text-center">
                        <h2>Contact Us</h2>
                        <span class="title-line"><i class="fa fa-car"></i></span>
                        <p>Feel free to Contact us anytime ! Your query is our priority </p>
                        {% if valid %}
                        <h2>Form Submitted, We will contact you ASAP</h2>
                        {% endif %}
                    </div>
                </div>
                <!-- Page Title End -->
            </div>
        </div>
    </section>
    <!--== Contact Page Area Start ==-->
    <div class="contact-page-wrao section-padding ">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 m-auto">
                    <div class="contact-form">
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-lg-6 col-md-6">
                                    <div class="name-input">
                                        <input type="text" placeholder="Full Name" name="user_name">
                                    </div>
                                </div>

                                <div class="col-lg-6 col-md-6">
                                    <div class="email-input">
                                        <input type="email" placeholder="Email Address" name="user_email">
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-6 col-md-6">
                                    <div class="website-input">
                                        <input type="text" placeholder="Mobile" name="user_mobile">
                                    </div>
                                </div>

                                <div class="col-lg-6 col-md-6">
                                    <div class="subject-input">
                                        <input type="text" placeholder="Subject" name="user_subject">
                                    </div>
                                </div>
                            </div>

                            <div class="message-input">
                                <textarea name="user_message" cols="30" rows="10" placeholder="Message" ></textarea>
                            </div>

                            <div class="input-submit">
                                <button type="submit">Submit Message</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--== Contact Page Area End ==-->
{% endblock content %}

templates/login.html
{% extends 'master.html' %}

{% block content %}


    <!--== Page Title Area Start ==-->
    <section id="page-title-area" class="section-padding overlay">
        <div class="container">
            <div class="row">
                <!-- Page Title Start -->
                <div class="col-lg-12">
                    <div class="section-title  text-center">
                        <h2>Login</h2>
                        <span class="title-line"><i class="fa fa-car"></i></span>
                        <h2>Please Enter the Details</h2>
                    </div>
                </div>
                <!-- Page Title End -->
            </div>
        </div>
    </section>
    <!--== Page Title Area End ==-->

    <!--== Login Page Content Start ==-->
    <section id="lgoin-page-wrap" class="section-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-8 m-auto">
                	<div class="login-page-content">
                		<div class="login-form">


							<form  method="post">
                                {% csrf_token %}

                            {% if login %}
                                <h3>Welcome Back!</h3>
								<div class="username">
									<input type="text"  id="user_email" name="user_email" required placeholder="Email or Username">
								</div>
                            {% if pass1 %}
                                <p>Username Doesn't Exist</p>
                                {% endif %}
                            <div class="password">
									<input type="password" id="user_password" name="user_password" required placeholder="Password">
								</div>
                            {% if pass2 %}
                                 <p>Invali Password</p>
                                {% endif %}
								<div class="log-btn">
									<button type="submit"><i class="fa fa-sign-in" ></i> Log In</button>
								</div>
                            {% if pass %}
                                 <h6>Please Login to Access</h6>
                                {% endif %}
                            {% endif %}
                                {% if vl %}
                                 <script>alert("Please Verify to access Your Account,Verification Link Sent on the Email")</script>
                                {% endif %}
                            {% if vf %}
                                 <script>alert("Please Verify First, Verification Link Has been already Sent")</script>
                                {% endif %}



                            {% if fp %}
                                <h3>OTP Generation</h3>
								<div class="username">
									<input type="text"  id="user_email" name="user_email" required placeholder="Email or Username">
								</div>
                                {% if not_sent %}
                                <p>Username Doesn't Exist</p>
                                {% endif %}

                                <div class="log-btn">
                                <button type="submit" id="otp_gen"><i class="fa fa-sign-in" ></i> Generate Otp</button>
								</div>
                                <div class="password">
									<input type="password" id="otp_gen" name="otp_gen" style="display: none"  value=""   placeholder="Enter OTP to regenerate Password">
								</div>

                            {% endif %}


                                {% if otp_gen %}
                                    <h3>Choose Password</h3>
                                <div class="username">
									<input type="text"   id="user_email" name="user_email" value="{{ em }}" readonly="True" placeholder="Email or Username">
								</div>
                                    <div class="password">
									<input type="password" id="otp_gen" name="otp_gen"   required placeholder="Enter OTP to regenerate Password">
								</div>
                                    {% if valid %}
                                <p>OTP Doesn't Match</p>
                                {% endif %}
                                    <div class="password">
									<input type="password" id="new_password" name="new_password" required placeholder="New Password"
                                    pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}"
                                           title="Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters">
								</div>
                                    <div class="password">
									<input type="password" id="confirm_password" name="confirm_password" required placeholder="Confirm Password">
								</div>
                                     <div class="log-btn">
                                <button type="submit" id="otp_gen"><i class="fa fa-sign-in" ></i> Generate Password</button>
								</div>

                            {% endif %}
							</form>
                		</div>


                    {% if login %}
                		<div class="create-ac">
                            <p><a href="{% url "front_app:forgetpassword" %}">Forget Password</a></p>
                        <p>Don't have an account? <a href={% url "front_app:signup" %}>Sign Up</a></p>
                		</div>
                    {% endif %}

                     {% if fp %}
                         <div class="create-ac">
                			<p>Don't have an account? <a href={% url "front_app:signup" %}>Sign Up</a></p>
                         </div>
                     {% endif %}
                    {% if otp_gen %}
                         <div class="create-ac">
                			<p>Don't have an account? <a href={% url "front_app:signup" %}>Sign Up</a></p>
                         </div>
                     {% endif %}



                	</div>
                </div>
        	</div>
        </div>
    </section>
    <!--== Login Page Content End ==-->

{% endblock content %}

{% block jquery %}
<script>


 $("#otp_gen").click(function(){
     var password = document.getElementById("new_password");
   var confirm_password = document.getElementById("confirm_password");

function validatePassword(){
  if(password.value != confirm_password.value) {
    confirm_password.setCustomValidity("Passwords Don't Match");
  } else {
    confirm_password.setCustomValidity('');
  }
}

password.onchange = validatePassword;
confirm_password.onkeyup = validatePassword;
 });



</script>
{% endblock %}

templates/master.html
<!DOCTYPE html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--=== Favicon ===-->
    <link rel="shortcut icon" href="/assets/logo.png" type="image/x-icon" />

    <title>AdRENTure Car-Hire</title>

    <!--=== Bootstrap CSS ===-->
    <link href="/assets/css/bootstrap.min.css" rel="stylesheet">
    <!--=== Slicknav CSS ===-->
    <link href="/assets/css/plugins/slicknav.min.css" rel="stylesheet">
    <!--=== Magnific Popup CSS ===-->
    <link href="/assets/css/plugins/magnific-popup.css" rel="stylesheet">
    <!--=== Owl Carousel CSS ===-->
    <link href="/assets/css/plugins/owl.carousel.min.css" rel="stylesheet">
    <!--=== Gijgo CSS ===-->
    <link href="/assets/css/plugins/gijgo.css" rel="stylesheet">
    <!--=== FontAwesome CSS ===-->
    <link href="/assets/css/font-awesome.css" rel="stylesheet">
    <!--=== Theme Reset CSS ===-->
    <link href="/assets/css/reset.css" rel="stylesheet">
    <!--=== Main Style CSS ===-->
    <link href="/assets/css/style.css" rel="stylesheet" type="text/css" media="screen" >
    <!--=== Responsive CSS ===-->
    <link href="/assets/css/responsive.css" rel="stylesheet">

    <link href="/assets/assets_admin/css/bootstrap-datetimepicker.min.css" rel='stylesheet' type='text/css' />



</head>

<body class="loader-active">

    <!--== Preloader Area Start ==-->
    <div class="preloader">
        <div class="preloader-spinner">
            <div class="loader-content">
                <img src="/assets/img/preloader.gif" alt="JSOFT">
            </div>
        </div>
    </div>
    <!--== Preloader Area End ==-->
<div>
    <!--== Header Area Start ==-->
    <header id="header-area" class="fixed-top">
        <!--== Header Top Start ==-->
        <div id="header-top" class="d-none d-xl-block">
            <div class="container">
                <div class="row">
                    <!--== Social Icons End ==-->
                </div>
            </div>
        </div>
        <!--== Header Top End ==-->

        <!--== Header Bottom Start ==-->
        <div id="header-bottom">
            <div class="container">
                <div class="row">
                    <!--== Logo Start ==-->
                    <div class="col-lg-4">
                        <a href="{% url 'front_app:index' %}" class="logo">
                            <img src="/assets/images/logo.png" alt="JSOFT">
                        </a>
                    </div>
                    <!--== Logo End ==-->

                    <!--== Main Menu Start ==-->
                    <div class="col-lg-8 d-none d-xl-block">
                        <nav class="mainmenu alignright">
                            <ul>
                                <li ><a href="{% url 'front_app:index' %}">Home</a>
                                </li>
                                <li><a href="{% url 'front_app:about'%}">About</a></li>
                                <li><a href="{% url 'front_app:contact'%}">Contact</a></li>

                                <li><a href="#">Policy</a>
                                <ul class="aligncenter">
                                    <li><a href="/feepolicy">Fee Policy</a></li>
                                    <li><a href="/eligibilty/">Eligibility</a></li>


                                </ul>
                                </li>

                                <li><a class="mr-4" href="{% url 'front_app:team'%}">Team</a></li>
                                {% if request.session.authenticate %}
                                    <li><img   style="object-fit: fill ;height: 60px; width: 60px; border-radius: 100%; border: groove; border-color: #e0a800" src="/media/{{ request.session.image }}">
                                    <ul class="aligncenter">
                                    <li><a title="{{ request.session.email }}({{ request.session.rolename }})" class="btn btn-outline-warning btn-lg " href="#" ><h6> {{ request.session.name }} </h6></a>
                                        </li>
                                        {% if request.session.role_id == 4 %}
                                    <li><a href="/businessuser">Dashboard</a></li>
                                            {% elif request.session.role_id == 3 %}
                                    <li><a href="/user">Dashboard</a></li>
                                            {% elif request.session.role_id == 1 %}
                                    <li><a href="/manager">Dashboard</a></li>
                                            {% elif request.session.role_id == 2 %}
                                    <li><a href="/superuser">Dashboard</a></li>
                                            {% endif %}
                                    <li><a href="/show_bookings">My Bookings</a></li>
                                    <li><a href="/logout">Logout</a></li>
                                    </ul>

                                </li>
                                    <!--div class="btn-group">
                                    <button class="btn btn-secondary btn-lg dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        name
                                    </button>
                                    <div class="dropdown-menu">
                                        <ul>
                                        <li><a href="#">Dashboard</a></li>
                                    <li><a href="#">Account</a></li>
                                            <li><a href="/logout">Logout</a></li></ul>
                                     </div>
                                    </div-->

                                {% else %}

                                    <li>
                                        <a href="/login">Login</a>

                                </li>
                                {% endif %}


                            </ul>
                        </nav>
                    </div>
                    <!--== Main Menu End ==-->
                </div>
            </div>
        </div>
        <!--== Header Bottom End ==-->
    </header>
</div>
    <!--== Header Area End ==-->


    <div>
    {% block content %}
    {% endblock content %}
    </div>


<!--== Footer Area Start ==-->
    <section id="footer-area">
        <!-- Footer Widget Start -->
        <div class="footer-widget-area">
            <div class="container">
                <div class="row">
                    <!-- Single Footer Widget Start -->
                    <div class="col-lg-3 col-md-6">
                        <div class="single-footer-widget">
                            <h2>About Us</h2>
                            <div class="widget-body">
                                <img src="/assets/images/logo.png" alt="JSOFT">
                                <h2>A Car Hire Portal</h2>
                            </div>
                            <li><a href="{% url 'front_app:login' %}">Admin Login</a></li>
                        </div>
                    </div>
                    <!-- Single Footer Widget End -->

                    <!-- Single Footer Widget Start -->
                    <div class="col-lg-3 col-md-6">
                        <div class="single-footer-widget">
                            <h2>Write To us at</h2>
                            <div class="widget-body">
                                <p>For any Queries and Feedback</p>

                                <ul class="get-touch">
                                    <li><a href="https://in.linkedin.com/in/Harshit Gupta"><i class="fa fa-envelope"></i>harshitgupta007@gmail.com </a></li>
                                    <li><i class="fa fa-envelope"></i> palkinangla1396@gmail.com </li>
                                    <li><i class="fa fa-envelope"></i> 0395ankita@gmail.com </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <!-- Single Footer Widget End -->

                    <!-- Single Footer Widget Start -->
                    <div class="col-lg-3 col-md-6">
                        <div class="single-footer-widget">
                            <h2>Contact Us</h2>
                            <div class="widget-body">
                                <p>Always there for Assistance</p>

                                <ul class="get-touch">
                                    <li><i class="fa fa-mobile"></i> +91 7837278101</li>
                                    <li><i class="fa fa-mobile"></i> +91 8894526047</li>
                                    <li><i class="fa fa-mobile"></i> +91 8628003936</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <!-- Single Footer Widget End -->
                    <!-- Single Footer Widget Start -->
                    <div class="col-lg-3 col-md-6">
                        <div class="single-footer-widget">
                            <h2>Guided By</h2>
                            <div class="widget-body">

                                <ul class="get-touch">
                                    <li><i class="fa fa-user-plus"></i>Mr. Daljit Singh <br>(Industry Mentor)</li><br>
                                    <li><a href="http://sandeepsood.in/"><i class="fa fa-user-plus"></i>Dr. Sandeep Sood<br> (Faculty Mentor)</a></li>

                                </ul>
                        </div>
                    </div>
                    <!-- Single Footer Widget End -->
                </div>
            </div>
        </div>
        <!-- Footer Widget End -->
    </section>
    <!--== Scroll Top Area Start ==-->
    <div class="scroll-top">
        <img src="/assets/img/scroll-top.png" alt="JSOFT">
    </div>
    <!--== Scroll Top Area End ==-->



    <!--=======================Javascript============================-->
    <!--=== Jquery Min Js ===-->
    <script src="/assets/js/jquery-3.2.1.min.js"></script>
    <script src="/assets/assets_admin/js/moment.min.js" type="text/javascript"></script>
    <!--=== Jquery Migrate Min Js ===-->
    <script src="/assets/js/jquery-migrate.min.js"></script>
    <!--=== Popper Min Js ===-->
    <script src="/assets/js/popper.min.js"></script>
    <!--=== Bootstrap Min Js ===-->
    <script src="/assets/js/bootstrap.min.js"></script>
    <script src="/assets/assets_admin/js/bootstrap-datetimepicker.min.js"></script>
    <!--=== Gijgo Min Js ===-->
    <script src="/assets/js/plugins/gijgo.js"></script>
    <!--=== Vegas Min Js ===-->
    <script src="/assets/js/plugins/vegas.min.js"></script>
    <!--=== Isotope Min Js ===-->
    <script src="/assets/js/plugins/isotope.min.js"></script>
    <!--=== Owl Caousel Min Js ===-->
    <script src="/assets/js/plugins/owl.carousel.min.js"></script>
    <!--=== Waypoint Min Js ===-->
    <script src="/assets/js/plugins/waypoints.min.js"></script>
    <!--=== CounTotop Min Js ===-->
    <script src="/assets/js/plugins/counterup.min.js"></script>
    <!--=== YtPlayer Min Js ===-->
    <script src="/assets/js/plugins/mb.YTPlayer.js"></script>
    <!--=== Magnific Popup Min Js ===-->
    <script src="/assets/js/plugins/magnific-popup.min.js"></script>
    <!--=== Slicknav Min Js ===-->
    <script src="/assets/js/plugins/slicknav.min.js"></script>

    <!--=== Mian Js ===-->
    <script src="/assets/js/main.js"></script>

    {% block jquery %}
    {% endblock %}



</body>

</html>

templates/register.html
{% extends 'master.html' %}


{% block content %}

    <!--== Page Title Area Start ==-->
    <section id="page-title-area" class="section-padding overlay" xmlns="http://www.w3.org/1999/html">
        <div class="container">
            <div class="row">
                <!-- Page Title Start -->
                <div class="col-lg-12">
                    <div class="section-title  text-center">
                        <h2>Sign up</h2>
                        <span class="title-line"><i class="fa fa-car"></i></span>

                    </div>
                </div>
                <!-- Page Title End -->
            </div>
        </div>
    </section>
    <!--== Page Title Area End ==-->

    <!--== Login Page Content Start ==-->
    <section id="lgoin-page-wrap" class="section-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-md-8 m-auto">
                	<div class="login-page-content">
                		<div class="login-form">
                			<h3>Sign Up</h3>
							<form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                            {% if valid %}
                                <script>alert("form submit")</script>
                            {% endif %}
                            {% if invalid %}
                                <script>alert("form invalid")</script>
                            {% endif %}


								<div class="name">
									<div class="row">
										<div class="col-md-6">
											<input type="text" placeholder="First Name" name="user_fname"  pattern="[A-Za-z]{1,}" title="Enter Alphabets Only" id="user_fname" required >

										</div>
                                        <div class="col-md-6">
											<input type="text" placeholder="Last Name" name="user_lname" pattern="[A-Za-z]{1,}" title="Enter Alphabets Only">
										</div>

									</div>
								</div>
								<div class="username" aria-label="Username" aria-describedby="basic-addon1">
									<input type="email"  placeholder="Email" name="user_email" id="amf-input-user_email" value="" maxlength="255" onkeyup="if(this.length>255) this.value=this.value.substr(0,255)"required >
								</div>

								<div class="username">
									<input type="text" placeholder="Mobile" name="user_mobile" pattern="[789][0-9]{9}" required>
								</div>
                            <div class="date">
									<input type="date" placeholder="Enter D.O.B." name="user_dob" required>
								</div>
								<div class="password">
									<input type="password" id ="user_password" placeholder="Password" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}"
                                           title="Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters" name="user_password" required>
                                    <span toggle="#user_password" class="fa fa-fw fa-eye field-icon toggle-password text-right" style="float:left">Show_Password</span>
								</div>
                            <div class="password">
									<input type="password" id = "user_confirm_password" placeholder="Confirm Password" name="user_confirm_password" >
                                <span id='message'></span>
								</div>
                            <div class="form-group text-left" >


                                    <label class="mr-3"><strong>Gender</strong></label>
                                        <input type="radio" class="mx-2" name="user_gender" value="Male"><label>Male</label>
                                        <input type="radio" class="mx-2" name="user_gender" value="Female"><label>Female</label>


                                </div>


                                <div class="form-group">
                                <input type="file" id="BSbtninfo" name="user_image">

                                </div>



                            <div>
                                <div class="select2-dropdown form-group">
                                    <select name="select">
                                    <option>Select Role</option>
                                    <option value="3">User</option>
                                    <option value="4">Bussiness User</option>
                                </select>

								</div>

                            </div>
                                <div class="form-group text-left" >

                                        <input type="radio" class="mx-2" required  value="1"><label >Agree To the Company Fee Policy <a href="/feepolicy" target="_blank">Click Here</a> to view</label>

                                </div>
								<div class="log-btn">
									<button type="submit" onclick="letteronly(user_fname)" id = "abc" name="submit"><i class="fa fa-check-square"></i> Sign Up</button>
								</div>
							</form>
                		</div>
                		

                		<div class="create-ac">
                			<p>Have an account? <a href="{% url 'front_app:login' %}">Sign In</a></p>
                		</div>
                	</div>
                </div>
        	</div>
        </div>
    </section>





    <!--== Login Page Content End ==-->
{% endblock content %}

{% block jquery %}
    <script>
    var password = document.getElementById("user_password");
   var confirm_password = document.getElementById("user_confirm_password");

function validatePassword(){
  if(password.value != confirm_password.value) {
    confirm_password.setCustomValidity("Passwords Don't Match");
  } else {
    confirm_password.setCustomValidity('');
  }
}

password.onchange = validatePassword;
confirm_password.onkeyup = validatePassword;




$(".toggle-password").click(function() {

  $(this).toggleClass("fa-eye fa-eye-slash");
  var input = $($(this).attr("toggle"));
  if (input.attr("type") == "password") {
    input.attr("type", "text");
  } else {
    input.attr("type", "password");
  }
});



    </script>

{% endblock %}

templates/verify.html
{% extends "master.html" %}
{% block content %}


<section id="page-title-area" class="section-padding overlay">
        <div class="container">
            <div class="row">
                <!-- Page Title Start -->
                <div class="col-lg-12">
                    <div class="section-title  text-center">
                                {% if valid %}
                                <h2>You are Already Verified</h2>

                                {% endif %}
                                {% if good %}
                                <h2>Thanks For Verifying</h2>
                                {% endif %}
                                {% if nv %}
                                    <h2>Please Verify Your Account</h2>
                                    <span class="title-line"><i class="fa fa-car"></i></span>
                                    <h2><a href="verify.html">Click Here to Send Verification Link</a></h2>
                                {% endif %}
                    </div>
                </div>
                <!-- Page Title End -->
            </div>
        </div>
    </section>



{% endblock content %}