adminapp/urls.py
from django.conf.urls import url
from adminapp import views
app_name = 'adminapp'
urlpatterns = [
url(r'^$', views.index, name="index"),
url(r'^vehicle_details/', views.vehicle_details, name="vehicle_details"),
url(r'^vehicle_category/$', views.vehicle_category, name="vehicle_category"),
url(r'^vehicle_company/$', views.vehicle_company, name="vehicle_company"),
url(r'^showdata/$', views.showdata, name="showdata"),
url(r'^updatedata/$', views.updatedata, name="updatedata"),
url(r'^delete_data/$', views.delete_data, name="delete_data"),
url(r'^queries/$', views.queries, name="queries")
]

businessuserapp/urls.py
from django.conf.urls import url

from businessuserapp import views
from django.conf import settings

app_name = 'businessuserapp'


urlpatterns = [
        url(r'^$', views.business_index, name="business_index"),
        url(r'^vehicle_details/', views.vehicle_details, name="vehicle_details"),
        url(r'^vehicle_category/$', views.vehicle_category, name="vehicle_category"),
        url(r'^vehicle_company/$', views.vehicle_company, name="vehicle_company"),
        url(r'^showdata/$', views.showdata, name="showdata"),
        url(r'^updatedata/$', views.updatedata, name="updatedata"),
        url(r'^delete_data/$', views.delete_data, name="delete_data"),
        url(r'^mybookings/$', views.my_bookings),
        url(r'^chkreturn/', views.chkreturn),
        url(r'^balance/', views.balance)
]

front_app/urls.py
from django.conf.urls import url
from front_app import views


app_name = 'front_app'

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^error$',views.page_not_found,name="error"),
    url(r'^about/$',views.about,name="about"),
    url(r'^contact$',views.contact,name="contact"),
    url(r'^faq$',views.faq,name="faq"),
    url(r'^team$',views.help,name="team"),
    url(r'^login$', views.login, name="login"),
    url(r'^signup$', views.signup, name="signup"),
    url(r'^masteruser/$', views.master, name="master"),
    url(r'^forgetpassword/$', views.forgototp, name="forgetpassword"),
    url(r'^car-details/$', views.car_detail, name="car"),
    url(r'^update/$', views.profile, name="update"),
    url(r'^booking/$', views.booking, name="booking"),
    url(r'^invoice/$', views.invoice, name="invoice"),
    url(r'^confirm_booking/', views.confirm_booking),
    url(r'^show_bookings/', views.show_bookings),
url(r'^view_bookings/', views.view_current_book),
    url(r'^cancel_booking/', views.cancel_booking),
    url(r'^queries/', views.queries),
url(r'^user/', views.user_index)



]

managerapp/urls.py
from django.conf.urls import url
from managerapp import views
from django.conf import settings




app_name = 'managerapp'


urlpatterns = [
        url(r'^$', views.manager_index, name="manager_index"),
        #url(r'^vehicle_category/$', views.vehicle_category, name="vehicle_category"),
        url(r'^vehicle_company/$', views.vehicle_company, name="vehicle_company"),
        url(r'^vehicle_details/$', views.vehicle_details, name="vehicle_details"),
        url(r'^showdata/$', views.showdata, name="showdata"),
        url(r'^updatedata/$', views.updatedata, name="updatedata"),
        url(r'^delete_data/$', views.delete_data, name="delete_data"),
        url(r'^mybookings/$', views.my_bookings, name="my_bookings"),
        url(r'^chkreturn/', views.chkreturn),
        url(r'^balance/', views.balance),
url(r'^bankbalance/', views.earnings),
url(r'^show_other_vehicles/', views.show_other)
]

vehicle_hire/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from front_app import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^logout/',views.logout ), # url for logout
    url(r'^', include('front_app.urls')),
    url(r'^superuser/', include('adminapp.urls',namespace="superuser")),
    url(r'^manager/', include('managerapp.urls')),
    url(r'^businessuser/', include('businessuserapp.urls')),
    url(r'^changepassword/',views.updatepassword),
    url(r'^profileupdate/',views.profile),
    url(r'^policy/',views.policy),
url(r'^feepolicy/',views.feepolicy),
url(r'^member/',views.member),
url(r'^privacy/',views.privacy),
url(r'^eligibilty/',views.eligibilty),

    url(r'^dskjgheriugiurefhkusdjdowieuqhiurehf/',views.verify)
    #url(r'^fpassword/',views.fpassword)

]\
              +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

managerapp/models.py
from django.db import models

# Create your models here.



class VehicleCategories(models.Model):
    vehicle_category_name=models.CharField(max_length=225,default="",unique=True)
    vehicle_category_price=models.IntegerField(default=0)
    type_isactive=models.BooleanField(default=True)
    vehicle_id=models.AutoField(primary_key=True)


class VehicleCompany(models.Model):
    company_name = models.CharField(max_length=225, default="",null=False,unique=True)
    company_id = models.AutoField(primary_key=True)
    company_isactive = models.BooleanField(default=True)

    
class VehiclesDetails(models.Model):
    vehicle_ref_id = models.AutoField(primary_key=True)
    vehicle_name = models.CharField(max_length=225, default="")
    vehicle_description = models.CharField(max_length=225,default="")
    vehicle_image = models.CharField(max_length=225,default="",null=True)
    vehicle_isactive = models.BooleanField(default=True)
    company_id = models.ForeignKey(VehicleCompany,on_delete=models.CASCADE,default="")
    vehicle_id = models.ForeignKey(VehicleCategories,on_delete=models.CASCADE,default="")
    u_email=models.CharField(max_length=225,default="")
    vehicle_isavailable=models.BooleanField(default=True)
    vehicle_price=models.IntegerField(default=0)
    vehicle_model=models.BigIntegerField(default=0)
    seats=models.CharField(max_length=255,default="")
    airbags = models.CharField(max_length=255,default="")
    abs=models.BooleanField(default=False)
    transmission=models.CharField(max_length=20,default="")

managerapp/forms.py
from django import forms
from managerapp.models import VehicleCategories, VehicleCompany, VehiclesDetails


class VehicleCategoryForm(forms.ModelForm):
    class Meta():
        model = VehicleCategories
        exclude = [
                    "vehicle_category_name",
                    "vehicle_category_price",
                    "type_isactive",
                    "vehicle_id"
                ]

class VehicleCompanyForm(forms.ModelForm):
    class Meta():
        model = VehicleCompany
        exclude = [
                    "company_name",
                    "company_id",
                    "company_isactive"
                    ]
class VehicleDetailsForm(forms.ModelForm):
    class Meta():
        model = VehiclesDetails
        exclude = [
                    "vehicle_ref_id",
                    "vehicle_name",
                    "vehicle_description",
                    "vehicle_image",
                    "vehicle_isactive",
                    "company_id",
                    "vehicle_id",
                    "u_email",
                    "vehicle_isavailable",
                    "vehicle_price",
                    "vehicle_model",
            "seats",
            "airbags",
            "abs",
            "transmission"
                     ]

managerapp/views.py
from django.shortcuts import render,redirect
import datetime as dt
import authorize as au
from managerapp.models import VehicleCompany,VehicleCategories,VehiclesDetails
from front_app.models import MySiteUser,booking_details
from front_app.forms import BookingForm
from django.core.files.storage import FileSystemStorage
from managerapp.forms import VehicleCategoryForm, VehicleCompanyForm, VehicleDetailsForm
import math
from django.db.models import Sum
from django.db.models import Q

# Create your views here.
def manager_index(request):

    try:
        auth = au.authorizeuser(request.session['authenticate'],request.session['role_id'],1)
        email = request.session['email']
        siteuserdata = MySiteUser.objects.get(user_email=email)
    except:
        return redirect("/login")
    if auth==True:
        return render(request,"manager.html",{"su":siteuserdata})
    else:
        auth,message = auth
        if (message=="Not Logged In"):
            return render(request,"login.html",{"pass":True})
        elif(message=="Wrong Level"):
            return render(request,"404.html",{"pass":True})

def business_index(request):
    try:

        auth = au.authorizeuser(request.session['authenticate'],request.session['role_id'],4)
        email = request.session['email']
        siteuserdata = MySiteUser.objects.get(user_email=email)
    except:
        return redirect("/login")
    if auth==True:
        return render(request,"manager.html",{'su':siteuserdata})
    else:
        auth,message = auth
        if (message=="Not Logged In"):
            return render(request,"login.html",{"pass":True})
        elif(message=="Wrong Level"):
            return render(request,"404.html",{"pass":True})









def vehicle_company(request):
    try:
        auth = au.authorizeuser(request.session['authenticate'],request.session['role_id'],1)
        email = request.session['email']
        siteuserdata = MySiteUser.objects.get(user_email=email)
    except:
        return redirect("/login")
    if auth==True:
            try:
                if (request.method == "POST"):
                    form = VehicleCompanyForm(request.POST)
                    if form.is_valid():
                        f1 = form.save(commit=False)
                        f1.company_name = (request.POST['company_name']).capitalize()
                        f1.save()
                        return render(request, "vehiclecompanies.html", {'valid': True})
                    else:
                        return render(request, "vehiclecompanies.html", {'invalid': True})
                return render(request, "vehiclecompanies.html")
            except:
                return render(request, "vehiclecompanies.html", {'exist': True})
    else:
        auth,message = auth
        if (message=="Not Logged In"):
            return render(request,"login.html",{"pass":True})
        elif(message=="Wrong Level"):
            return render(request,"404.html",{"pass":True})





def vehicle_details(request):


    try:
        auth = au.authorizeuser(request.session['authenticate'],request.session['role_id'],1)
        email = request.session['email']
        siteuserdata = MySiteUser.objects.get(user_email=email)
    except:
        return redirect("/login")
    if auth==True:
        year = int(dt.datetime.now().strftime(" %Y "))
        get_role = request.session['role_id']
        get_email = request.session['email']
        companydata = VehicleCompany.objects.all()
        companycategorydata = VehicleCategories.objects.all()
        userdata = VehiclesDetails.objects.all()
        if get_role == 4:
            for i in userdata:
                if get_email == i.u_email:
                    return redirect("/businessuser/showdata")
        if request.method == "POST":
            user_image = None
            if request.FILES:
                myfile = request.FILES['vehicle_image']  # type of file control name ??
                fs = FileSystemStorage()
                filename = fs.save(myfile.name, myfile)
                fs.url(filename)
                user_image = myfile.name

            form = VehicleDetailsForm(request.POST)
            if form.is_valid():
                f = form.save(commit=False)
                f.vehicle_name = request.POST['vehicle_name']
                f.u_email = request.session['email']
                f.vehicle_id_id = request.POST['veh_id']
                f.company_id_id = request.POST['sel']
                f.vehicle_description = request.POST['vehicle_description']
                f.vehicle_price = request.POST['vehicle_price']
                f.vehicle_model = request.POST['vehicle_model']
                f.abs = request.POST['abs']
                f.transmission = request.POST['transmission']
                f.airbags = request.POST['airbags']
                f.seats = request.POST['seats']
                # f.vehicle_price= int(f.vehicle_price) + int(base_price)
                f.vehicle_image = user_image
                f.save()
                return render(request, "vehicledetails.html",
                              {'valid': True, 'cd': companydata, "ccd": companycategorydata, 'yr': year})
            else:
                return render(request, "vehiclecategories.html", {'invalid': True})

        return render(request, "vehicledetails.html", {'cd': companydata, "ccd": companycategorydata, 'yr': year})
    else:
        auth,message = auth
        if (message=="Not Logged In"):
            return render(request,"login.html",{"pass":True})
        elif(message=="Wrong Level"):
            return render(request,"404.html",{"pass":True})



def showdata(request):
    try:
        auth = au.authorizeuser(request.session['authenticate'],request.session['role_id'],1)
        email = request.session['email']
        siteuserdata = MySiteUser.objects.get(user_email=email)
    except:
        return redirect("/login")
    if auth==True:
        email = request.session['email']
        ccd = VehicleCategories.objects.all()
        userdata = VehiclesDetails.objects.filter(u_email=email)
        return render(request, "view_cars.html", {'ud': userdata, 'ccd': ccd})
    else:
        auth,message = auth
        if (message=="Not Logged In"):
            return render(request,"login.html",{"pass":True})
        elif(message=="Wrong Level"):
            return render(request,"404.html",{"pass":True})


def delete_data(request):
    try:
        auth = au.authorizeuser(request.session['authenticate'],request.session['role_id'],1)
        email = request.session['email']
        siteuserdata = MySiteUser.objects.get(user_email=email)
    except:
        return redirect("/login")
    if auth==True:
        carid = request.GET['id']
        try:
            deleteUser = VehiclesDetails.objects.get(vehicle_ref_id=carid)
            deleteUser.delete()
            if request.session['role_id'] == 4:
                return redirect("businessuserapp:showdata")
            else:
                return redirect("managerapp:showdata")

        except:
            pass
    else:
        auth,message = auth
        if (message=="Not Logged In"):
            return render(request,"login.html",{"pass":True})
        elif(message=="Wrong Level"):
            return render(request,"404.html",{"pass":True})


def updatedata(request):
    try:
        auth = au.authorizeuser(request.session['authenticate'],request.session['role_id'],1)
        email = request.session['email']
        siteuserdata = MySiteUser.objects.get(user_email=email)
    except:
        return redirect("/login")
    if auth==True:
        year = int(dt.datetime.now().strftime(" %Y "))
        companydata = VehicleCompany.objects.all()
        companycategorydata = VehicleCategories.objects.all()
        userdata = VehiclesDetails.objects.all()
        get_id = request.GET['id']
        userdata = VehiclesDetails.objects.get(vehicle_ref_id=get_id)
        if request.method == "POST":
            user_image = userdata.vehicle_image
            if request.FILES:
                myfile = request.FILES['vehicle_image']
                fs = FileSystemStorage()
                filename = fs.save(myfile.name, myfile)
                fs.url(filename)
                user_image = myfile.name

            name = (request.POST["vehicle_name"]).capitalize()
            model = request.POST['vehicle_model']
            price = request.POST['vehicle_price']
            desc = request.POST["vehicle_description"]
            image = user_image

            update = VehiclesDetails(vehicle_ref_id=get_id, vehicle_name=name, vehicle_description=desc,
                                     vehicle_image=image, vehicle_price=price, vehicle_model=model)
            update.save(update_fields=["vehicle_name", "vehicle_description", "vehicle_image", "vehicle_price",
                                       "vehicle_model"])
            if request.session['role_id'] == 4:
                return redirect("businessuserapp:showdata")
            else:
                return redirect("managerapp:showdata")
        return render(request, "update_cars.html",
                      {'vd': userdata, 'yr': year, 'ccd': companycategorydata, 'cd': companydata})
    else:
        auth,message = auth
        if (message=="Not Logged In"):
            return render(request,"login.html",{"pass":True})
        elif(message=="Wrong Level"):
            return render(request,"404.html",{"pass":True})

def my_bookings(request):
    try:
        auth = au.authorizeuser(request.session['authenticate'],request.session['role_id'],request.session['role_id'])
        email = request.session['email']
        siteuserdata = MySiteUser.objects.get(user_email=email)
    except:
        return redirect("/login")
    if auth==True:
        if request.session['role_id'] == 1 :
            book_id=[]
            try:
                if request.method == "POST":

managerapp/templates/chkreturn.html
{% extends 'admin_master.html' %}


{% block content %}

<div id="page-wrapper">
        <div class="main-page">
            <div class="row">
                <h3 class="title1">Return</h3>
                <div class="form-three widget-shadow">
                    <form method="POST" enctype="multipart/form-data" class="form-horizontal">
                        {% csrf_token %}

                        <div class="col-xs-6">
  <h1>
    <a href="/">
      <img  src="/assets/img/logo.png">
    </a>
  </h1>
</div>
                    <div class="col-xs-6 text-right">
                        {% if bd.is_active == True and bd.is_returned == False %}
                            <h1 style="color:green">Active</h1>
                            {% endif %}
                        {% if bd.is_active == False and bd.is_returned == True and bd.cancellation_time != ""  %}
                            <h1 style="color:Red">Booking Cancelled</h1>

                            {% endif %}
                        {% if bd.is_active == False and bd.is_returned == True and bd.cancellation_time == ""  %}
                            <h1 style="color:blue">Completed Successfully</h1>

                            {% endif %}
                        <a href="{% url 'front_app:invoice' %}?id={{ bd.booking_id }}" >

                            <h2>INVOICE</h2></a>

                      <h1><small> #{{ bd.invoice }}</small></h1>

                    </div>
                    <hr><br><br><br>

                                <div class="form-group has-dark">
										<label class="col-md-2 control-label">Booking Date</label>
										<div class="col-md-5">
											<div class="input-group input-icon right">
												<span class="input-group-addon">
													<i class="fa fa-calendar"></i>
												</span>
												<input readonly  class="form-control1" value="{{ bd.booking_date }}" type="text" >
											</div>
                                        </div></div>

                    <div class="form-group has-dark">
										<label class="col-md-2 control-label">Pick-Up Date-Time</label>
										<div class="col-md-5">
											<div class="input-group input-icon right">
												<span class="input-group-addon">
													<i class="fa fa-calendar"></i>
												</span>
												<input readonly name="start_date" class="form-control1" value="{{ bd.start_date }}" type="text" >
											</div>
                                        </div></div>

                    <div class="form-group has-dark">
										<label class="col-md-2 control-label">Return Date-Time</label>
										<div class="col-md-5">
											<div class="input-group input-icon right">
												<span class="input-group-addon">
													<i class="fa fa-calendar"></i>
												</span>
												<input readonly name="end_date" class="form-control1" value="{{ bd.end_date }}" type="text" >
											</div>
                                        </div></div>


                    <div class="form-group has-dark">
                        <label class="col-sm-2 control-label">Vehicle Name</label>
                        <div class="col-sm-5">
                            <div class="input-group input-icon right">
												<span class="input-group-addon">
													<i class="fa fa-car"></i>
												</span>
                            <input type="text" class="form-control"  value="{{ bd.vehicle_info.company_id.company_name }} {{ bd.vehicle_info.vehicle_name }}">
                        </div>
                        </div>
                    </div>

                    <div class="form-group has-dark">
                        <label class="col-sm-2 control-label">User Email</label>
                        <div class="col-sm-5">
                            <div class="input-group input-icon right">
												<span class="input-group-addon">
													<i class="fa fa-envelope"></i>
												</span>
                            <input readonly type="email" class="form-control1" placeholder="{{ bd.user_detail }}">
                        </div>
                        </div>
                    </div>



                        <div class="form-group" >
                            <label class="col-sm-2 control-label">Documents</label>
                            <div class="col-sm-8">
                                    <div class="radio-inline">
                                        <label><input type="radio" name="documents"  value="yes" required>Yes</label>
                                    </div>
                                <div class="radio-inline">
                                        <label><input type="radio"  name="documents" value="no"  required>No</label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group" id="documents" style="display:none;">
                            <label class="col-sm-2 control-label">Document Fine</label>
                            <div class="col-sm-8">
                                <input type="number" class="form-control1" name="fine" placeholder="Enter Fine Amount">
                            </div>
                        </div>


                        <div class="form-group" >
                            <label class="col-sm-2 control-label">Damage</label>
                            <div class="col-sm-8">
                                    <div class="radio-inline">
                                        <label><input type="radio" id="damager" name="damage" value="damage" required>Yes</label>
                                    </div>
                                <div class="radio-inline">
                                        <label><input type="radio" name="damage" value="nodamage" required>No</label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group" id="damage" style="display:none;" >
                            <label class="col-sm-2 control-label">Insurance Coverage</label>
                            <div class="col-sm-8">
                                    <div class="radio-inline">
                                        <label><input type="radio"  name="covered" value="covered" >Yes</label>
                                    </div>
                                <div class="radio-inline">
                                        <label><input type="radio" name="covered" value="notcovered">No</label>
                                </div>
                            </div>
                        </div>


                        <div class="form-group" id="no_cover" style="display:none;">
                            <label class="col-sm-2 control-label">Damage Charges</label>
                            <div class="col-sm-8">
                                <input type="number" name="damage_amount" placeholder="Enter Damage Amount"  class="form-control1"  >
                            </div>
                        </div >





                        <div class="form-group" >
                            <label class="col-sm-2 control-label">Exceed</label>
                            <div class="col-sm-8">
                                    <div class="radio-inline">
                                        <label><input type="radio" name="exceed" value="1" required>Yes</label>
                                    </div>
                                <div class="radio-inline">
                                        <label><input type="radio" name="exceed" value="0" required>No</label>
                                </div>
                            </div>
                        </div>


                        <div class="form-group ">
                            <div class="control-label col-sm-6">
                                <button  type="submit" class="btn btn-default">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
</div>
<script>
$(document).ready(function(){
$("input[type='radio']").change(function(){
if($(this).val()=="no")
{
$("#documents").show();
}
if($(this).val()=="yes")
{
$("#documents").hide();
}


if($(this).val()=="damage")
{
$("#damage").show();
}
if($(this).val()=="nodamage")
{
$("#damage").hide();
}

if($(this).val()=="notcovered")
{
$("#no_cover").show();
}
if($(this).val()=="covered")
{
$("#no_cover").hide();
}



});
});



</script>
{% endblock %}

managerapp/templates/view_cars.html
{% extends 'admin_master.html' %}


{% block content %}


<div id="page-wrapper">
    <div class="main-page">
        <div class="row">
            <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a><i class="fa fa-angle-right"></i>Gallery</li>
        </ol>
            <div class=" btn btn-group-justified" role="group" aria-label="Basic example">
                <a class="btn btn-secondary" data-filter="*">All</a>
                {% if ccd %}
                {% for i in ccd  %}
                    <a class="btn btn-secondary " data-filter=".{{ i.vehicle_category_name }}">{{ i.vehicle_category_name }}</a>
                {% endfor %}
                {% endif %}
            </div>
            <div class="card">
                {% if ud %}
                {% for i in ud %}
                    <div class="col-md-3 {{ i.vehicle_id.vehicle_category_name }}">
                        <div  style="width: 18rem; border: groove">
                            <img class="card-img-top" height="170" width="282" src="/media/{{ i.vehicle_image }}" alt="Card image cap">
                            <div class="card-body ">
                                <h3 class="card-title pb-2">{{ i.company_id.company_name }} {{ i.vehicle_name }}</h3>
                                <h5>{{ i.vehicle_id.vehicle_category_name }},{{ i.vehicle_model }}</h5>
                                <h5>{{ i.u_email }}</h5>
                                <h4>Rs.{{ i.vehicle_price }}/hour</h4>
                                {% if request.session.role_id == 2 %}
                                    <h5>{{ i.u_email }}</h5>
                                {% endif %}
                                {% if request.session.role_id == 4%}
                                    <a class="btn btn-primary btn-sm" href="{% url 'businessuserapp:delete_data' %}?id={{ i.vehicle_ref_id }}">Delete</a>
                                    <a class="btn btn-primary btn-sm" href="{% url 'businessuserapp:updatedata' %}?id={{ i.vehicle_ref_id }}">Edit</a>
                                    {% elif request.session.role_id == 1  %}
                                    <a class="btn btn-primary btn-sm"  href="{% url 'managerapp:delete_data' %}?id={{ i.vehicle_ref_id }}">Delete</a>
                                    <a class="btn btn-primary btn-sm" href="{% url 'managerapp:updatedata' %}?id={{ i.vehicle_ref_id }}">Edit</a>
                                      {% elif request.session.role_id == 2  %}
                                    <a class="btn btn-primary btn-sm"  href="{% url 'superuser:delete_data' %}?id={{ i.vehicle_ref_id }}">Delete</a>
                                    <a class="btn btn-primary btn-sm" href="{% url 'superuser:updatedata' %}?id={{ i.vehicle_ref_id }}">Edit</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
</div>


<!--div class="agile3-grids mt-5">
    {% if ud %}
    {% for i in ud %}
                <div class="col-md-3">
                    <a class="example-image-link" href="#" data-lightbox="example-set" data-title="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vitae cursus ligula">
                    <img src="/media/{{ i.vehicle_image }}" alt="image name" style="height: 200px; width: 200px;">
                    <h3>{{ i.company_id.company_name }} {{ i.vehicle_name }}</h3>

                    <h5>{{ i.vehicle_id.vehicle_category_name }}</h5>
                    <h4>Rs.{{ i.vehicle_price }}/hour</h4>
                    {% if request.session.role_id == 4%}
                    <a href="{% url 'businessuserapp:delete_data' %}?id={{ i.vehicle_ref_id }}"><button> Delete</button></a>
                    <a href="{% url 'businessuserapp:updatedata' %}?id={{ i.vehicle_ref_id }}"><button> Edit</button></a>
                    {% elif request.session.role_id == 1 %}
                    <a href="{% url 'managerapp:delete_data' %}?id={{ i.vehicle_ref_id }}"><button> Delete</button></a>
                    <a href="{% url 'managerapp:updatedata' %}?id={{ i.vehicle_ref_id }}"><button> Edit</button></a>
                    {% else %}
                    <a href="{% url 'adminapp:delete_data' %}?id={{ i.vehicle_ref_id }}"><button> Delete</button></a>
                    <a href="{% url 'adminapp:updatedata' %}?id={{ i.vehicle_ref_id }}"><button> Edit</button></a>
                    {% endif %}
                    </a>
                </div>
    {% endfor %}
    {% else %}
        <h2>no data found</h2>
    {% endif %}
</div-->


<div class="clearfix">
    <script src="/assets/assets_admin/js/lightbox-plus-jquery.min.js"> </script>
</div>


<!-- script-for sticky-nav -->
<script>
$(document).ready(function() {
 var navoffeset=$(".header-main").offset().top;
 $(window).scroll(function(){
    var scrollpos=$(window).scrollTop();
    if(scrollpos >=navoffeset){
        $(".header-main").addClass("fixed");
    }else{
        $(".header-main").removeClass("fixed");
    }
 });
});
</script>
<!-- /script-for sticky-nav -->


{% endblock content %}